;
;   Catálogo Base
;   Licenciado sob a licença MIT.
;

[Catalog.Base]

; Nome de exibição do catálogo
DisplayName="Catálogo Base"

; Descrição do catálogo
Description="Contém o necessário para criar uma imagem leve do Ubuntu Noble."

; Versão do catálogo
Version="1.0.0"

; Autores
Authors=Jppgmx

[Catalog.Base.Global]

; Tamanho preferido para o sistema.
PreferredSize=4G