;
;   System Updates Add-on
;   Licenciado sob a licença MIT.
;

[Addon.Updates]

; Nome de exibição do add-on
DisplayName="System Updates"

; Descrição do add-on
Description="Atualiza a estrutura do sistema operacional para a versão mais recente disponível."

; Versão do add-on
Version="1.0.0"

; Autores
Authors="Jppgmx"
