;
;   Custom Catalog
;   Licensed under the MIT license.
;

[Catalog.YourCatalog]

; Display name
DisplayName="Custom Catalog"

; Description
Description="Short description of the catalog."

; Version
Version="1.0.0"

; Authors
Authors="YourName"

[Catalog.YourCatalog.Global]

; Preferred system size
PreferredSize=4G
