#!/bin/bash
#
# UNMM LXQt Add-on
# Sob licença MIT
#
# Criador: João Paulo (o Jppgmx)
#

ADDON_NAME="LXQt-nogdm"
ADDON_DISPLAY_NAME="LXQt Desktop Environment"
ADDON_VERSION="1.0.0"
ADDON_DESCRIPTION="Instala o ambiente de desktop LXQt com o básico sem gerenciador de login (GDM). Isso implica sempre usar startx para iniciar a sessão gráfica."

_ADDON_PACKAGES=(
    "xorg" "xinit" "mesa-utils"
    "lxqt-core" "openbox" "lxqt-policykit"
    "pulseaudio" "pavucontrol" "alsa-utils" "fonts-noto"
    "qterminal" "qps" "featherpad" "htop" "gvfs-backends" "gvfs-fuse" "eject"
)

#
#   Parâmetros de um Add-on:
#
#   ADDON_INSTALL_ARG_MOUNTPOINT        - ponto de montagem do sistema de arquivos raiz
#   ADDON_INSTALL_ARG_HOSTNAME          - nome do host da instalação
#   ADDON_INSTALL_ARG_USERNAME          - nome do usuário padrão
#   ADDON_INSTALL_ARG_PASSWORD          - senha do usuário padrão
#   ADDON_INSTALL_ARG_DEVICE            - dispositivo de disco alvo
#   ADDON_INSTALL_ARG_BOOTMODE          - modo de boot (bios, uefi ou hybrid)
#   ADDON_INSTALL_ARG_DISKIMAGEPATH     - caminho do arquivo de imagem de disco
#   ADDON_INSTALL_ARG_SIZE              - tamanho do disco em GB
#   ADDON_INSTALL_ARG_INSTALLED_CATALOG - catálogo instalado pela CLI
#
addon_install() {
    log_info "Instalando ambiente gráfico LXQt minimal..."
    if ! chroot_call_logged "$ADDON_INSTALL_ARG_MOUNTPOINT" $APT_GET_COMMAND "${_ADDON_PACKAGES[@]}"; then
        log_error "Falha ao instalar pacotes do LXQt."
        return 1
    fi

    log_info "Configurando .xinitrc para o usuário padrão..."
    cat > "${ADDON_INSTALL_ARG_MOUNTPOINT}/home/${ADDON_INSTALL_ARG_USERNAME}/.xinitrc" <<EOF
#!/bin/sh
exec startlxqt
EOF

    log_verbose "Aplicando permissões ao .xinitrc..."
    chmod +x "${ADDON_INSTALL_ARG_MOUNTPOINT}/home/${ADDON_INSTALL_ARG_USERNAME}/.xinitrc"
    chroot_call_logged "$ADDON_INSTALL_ARG_MOUNTPOINT" chown "${ADDON_INSTALL_ARG_USERNAME}:${ADDON_INSTALL_ARG_USERNAME}" "/home/${ADDON_INSTALL_ARG_USERNAME}/.xinitrc"
}