;
;   LXQt Add-on
;   Licenciado sob a licença MIT.
;

[Addon.Lxqt]

; Nome de exibição do add-on
DisplayName="LXQt Desktop Environment"

; Descrição do add-on
Description="Instala o ambiente de desktop LXQt com o básico sem gerenciador de login (GDM). Isso implica sempre usar startx para iniciar a sessão gráfica."

; Versão do add-on
Version="1.0.0"

; Autores
Authors="Jppgmx"
