;
;   Build Tools Add-on
;   Licenciado sob a licença MIT.
;

[Addon.Buildtools]

; Nome de exibição do add-on
DisplayName="Ferramentas de Build"

; Descrição do add-on
Description="Instala as ferramentas de build essenciais para desenvolvimento do Linux."

; Versão do add-on
Version="1.0.0"

; Autores
Authors="Jppgmx"
